### ISSUE TITLE
amshan starter ikke etter oppdatering av Home Assistant

### ISSUE THREAD

**Issue by mloraas** [toreamun/amshan-homeassistant#78] opened 2024-12-21 17:14 UTC
Ser ut til at amshan kræsjer etter oppdatering til 2024.12.5

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: December 20, 2024 at 23:43:48 (1 occurrences)
Last logged: December 20, 2024 at 23:43:48

Setup failed for custom integration 'amshan': Requirements for amshan not found: ['amshan[serial]==2.1.1'].
```
```

Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: December 20, 2024 at 23:43:37 (3 occurrences)
Last logged: December 20, 2024 at 23:43:48

Unable to install package amshan[serial]==2.1.1: error: Failed to fetch: `https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve

```

**Comment by toreamun** [comment] 2024-12-22 19:34
The error message indicate a DNS problem:
Caused by: dns error: failed to lookup address information: Name does not resolve

The host files.pythonhosted.org resolves fine for me, but this addres is behind at a CDN I think, and the addresswa it resoles to may be different for each resolve. I suggest you try again. The address also support IPv6, so if you have a flawed IPv6 setup where your DNS resolves IPv6 addresses, but IPv6 connectivity is not supported the error may be permanent for you until IPv6 setup is fixed or DNS IPv6 resolving is turned off.

**Closed by toreamun** 2024-12-22 19:34 UTC

**Comment by mloraas** [comment] 2024-12-22 19:52
The problem arose after updating Home Assistant. No other changes made. IPv6 is disabled. The domain resolves fine when running ping from the command line Home Assistant.

I tried to remove the extension and uninstalling it from HACS, before reinstalling again. Now I am unable to add the integration. It starts loading saying "Please wait, starting configuration wizard for AMS HAN meter", but then fails with "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble".

I have tried several reboots of Home Assistant and also cleared the browser cache.

Getting this in the log:
`Unable to install package amshan[serial]==2.1.1: error: Failed to fetch: `https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve`

I am able to wget the file using the command line of Home Assistant.

**Comment by toreamun** [comment] 2024-12-22 23:25
What supervision version and OS versions and are you running? Seems to be DNS issues with latest versions.

Se https://github.com/home-assistant/supervisor/issues/5502 and maybe https://github.com/home-assistant/operating-system/issues/3726

**Comment by mloraas** [comment] 2024-12-23 00:32
Core: 2024.12.5
Supervisor: 2024.12.0
Operating System: 14.1
Frontend: 20241127.8

**Comment by Jernau** [comment] 2025-01-12 16:04
Exactly the same issue here. Definitely caused by a HA patch in December. 
I've built clean HA servers onto both a clean VM and a dedicated PC and the error always happens.
DNS is working from everywhere to everywhere including from the HA console to failed locations in the logs (github in my case).
Also tried beta channel - no change.

**Comment by mloraas** [comment] 2025-01-12 18:45
I moved over to NodeRED and this contrib: https://flows.nodered.org/node/node-red-contrib-ams-decoder

Works perfectly with the same local data pushed to my MQTT by the Tibber Pulse.

Took some fiddling to get used to NodeRED, but now I am happy that I took the time. Seems like a really powerful tool to have in the toolbox.

**Comment by mloraas** [comment] 2025-03-20 10:19
Moved back to amshan - now it seems to be working again!

**Comment by mloraas** [comment] 2025-04-02 23:33
...and the issue is back again. Now with a completely different Home Assistant install:

```
Logger: homeassistant.setup
Source: setup.py:275
First occurred: 01:31:29 (1 occurrences)
Last logged: 01:31:29

Setup failed for custom integration 'amshan': Requirements for amshan not found: ['amshan[serial]==2.1.1'].
```

```
Logger: homeassistant.util.package
Source: util/package.py:159
First occurred: 01:31:18 (3 occurrences)
Last logged: 01:31:29

Unable to install package amshan[serial]==2.1.1: error: Failed to fetch: `https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://files.pythonhosted.org/packages/aa/d4/883b6d951f4b7ea3c04bd45e751726e78dcc0beac6a7201431a3119cdd9b/amshan-2.1.1-py3-none-any.whl.metadata) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Name does not resolve Caused by: failed to lookup address information: Name does not resolve
```

I can ping from the command line of Home Assistant. That works.

**Comment by mloraas** [comment] 2025-04-03 00:05
Aaaaand, solved it:

https://github.com/home-assistant/core/issues/135054

Seems to be a DNS-issue, especially in combination with MikroTik equipment. Which I have at both locations where I had this issue.

Setting a different DNS-server solves it.
